services:
  - type: web
    name: JarvisXBot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7605281790:AAHhl2iUFuv0vtO4GvCsU3JQ5gQ5ED8wyx4
